### PR TITLE
Fix OHR cast; would not cast in some cases. Unsure why.

### PR DESCRIPTION
**Pull request by Ignose**

### CODE REVIEW

**Comment by frazazel** [comment]
You're working on an old branch. I merged your PR last week, then added a few commits of my own. Best practice is to make a new up-to-date branch to start your new commits on when you make a new PR.

I moved this task above the pajamas task, and if I try to merge this into the up-to-date main repo, then it creates a new task below pajamas instead of modifying the existing task.

**Comment by frazazel** [comment]
Also the _aug13Cast preference isn't recognized in goorbo's old libram version, so we'll either need to a dependency update, or instead use get("_aug13Cast", false) to tell libram what data type to convert it to, and what default value to use if we can't find the preference.

**Comment by frazazel** [comment]
It's not well documented, but goorbo has an engine modification that makes all tasks have `limit: {tries: 1}` if their limit is not explicitly set (see engine.ts, line 66, compliments of reverkiller). Adding that same default limit is not required.

Also, this task needs to not break for any user who doesn't have an august scepter.

**Comment by Ignose** [comment]
Made the changes requested.

**Comment by frazazel** [comment]
Almost. It's still showing up as a new task after pajamas instead of modifying the existing task that got moved to before pajamas. (It's important to cast the skill first so that mafia knows to prefer lefty over tot, etc.)

**Comment by Ignose** [comment]
I see; when I pulled origin it duplicated. Does this look better?

**Review by frazazel — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
