### PR TITLE
Leveling improvements

### PR DESCRIPTION
**Pull request by Alium58**
Uses `Feel Pride` for NEP and gators. 

Also uses `bowl sideways` opportunistically in NEP and gators. If it is available, use it. Leaving it to a future PR to fully support the bowling ball (stop using bowl straight up in time to use sideways for leveling)

Tested today and both are working for NEP. Pride properly got used when available and stopped attempting when used up for the day. Got to 13 before going to gators so didn't test that but I think low risk

### CODE REVIEW

**Comment by Alium58** [comment]
Example of using `feel pride`
```
[1125] The Neverending Party
Preference lastEncounter changed from Eldritch Tentacle to "plain" girl
Encounter: "plain" girl
Round 0: Alium wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 2 to 1
Round 0: Alium casts CURSE OF WEAKSAUCE!
Round 1: "plain" girl drops 9 attack power.
Round 1: "plain" girl drops 8 defense.
Round 1: Alium uses the porquoise-handled sixgun!
Round 2: "plain" girl takes 43 damage.
Round 2: You gain 25 Muscularity Points
Round 2: "plain" girl drops 8 attack power.
Round 2: "plain" girl drops 10 defense.
Round 2: Alium casts SING ALONG!
Round 3: "plain" girl drops 9 attack power.
Round 3: "plain" girl drops 8 defense.
Round 3: Alium casts FEEL PRIDE!
Round 4: "plain" girl drops 8 attack power.
Round 4: "plain" girl drops 8 defense.
Preference _feelPrideUsed changed from 1 to 2
Round 4: Alium attacks!
Round 5: "plain" girl takes 305 damage.
Round 5: "plain" girl drops 9 attack power.
Round 5: "plain" girl drops 10 defense.
...
Round 7: Alium wins the fight!
You gain 414 Meat
After Battle: Nanite Configuration 5426205 does the nanobot. Which is a dance like the robot, but smaller and harder to see.
Preference scrapbookCharges changed from 359 to 360
You acquire an item: electronics kit
You acquire an item: PB&J with the crusts cut off
You acquire an item: ponytail clip
After Battle: You gain 1796 Muscleboundness
You gain some Muscle points!
You gain a Level!
After Battle: You gain 581 Wizardliness
You gain some Mysticality points!
After Battle: You gain 578 Cheek
```

**Comment by Alium58** [comment]
Example of `bowl sideways`
```
[1125] The Neverending Party
Preference lastEncounter changed from burnout to jock
Encounter: jock
Round 0: Alium wins initiative!
Round 0: Alium casts CURSE OF WEAKSAUCE!
Round 1: jock drops 12 attack power.
Round 1: jock drops 10 defense.
Round 1: Alium casts BOWL SIDEWAYS!
Round 2: jock drops 11 attack power.
Round 2: jock drops 11 defense.
Preference _cosmicBowlingSkillsUsed changed from 27 to 28
Preference cosmicBowlingBallReturnCombats changed from -1 to 58
Round 2: Alium uses the porquoise-handled sixgun!
Round 3: jock takes 43 damage.
Round 3: You gain 25 Muscularity Points
Round 3: jock drops 12 attack power.
Round 3: jock drops 11 defense.
Round 3: Alium casts SING ALONG!
Round 4: jock drops 13 attack power.
Round 4: jock drops 12 defense.
Round 4: Alium attacks!
Round 5: jock takes 267 damage.
Round 5: jock drops 11 attack power.
Round 5: jock drops 12 defense.
...
Round 9: Alium wins the fight!
Your familiar gains a pound: Nanite Configuration 5426205, the 7 lb. Grey Goose
You gain 540 Meat
After Battle: Nanite Configuration 5426205 does a weird dance-like movement.
Preference scrapbookCharges changed from 361 to 362
You acquire an item: unremarkable duffel bag
You acquire an item: Purple Beast energy drink
You acquire an item: cosmetic football
You acquire an item: shoe ad T-shirt
After Battle: You gain 1030 Muscleboundness
You gain some Muscle points!
You gain a Level!
After Battle: You gain 245 Wizardliness
You gain some Mysticality points!
After Battle: You gain 315 Chutzpah
You gain some Moxie points!
```

**Review by frazazel — CHANGES_REQUESTED** [review]
trySkill() will already check if we have access to skills like feel pride and bowl sideways, and these skills don't need to be wrapped in an externalIf() if we're just checking if we can cast them. externalIf() is required for things like checking if you're at the level you want to be, or checking if your goose is fully charged.

**Review by frazazel — CHANGES_REQUESTED** [review]
In addition to not needing to check if we have Feel Pride and that we have casts of it left (tySkill() already handles that), we should be using Feel Pride late in the leveling chain, because hitting gooso exp increases the experience gain from future fights by a lot. We should add a check to make sure we're at least level 11 (gooso stats can sometimes take us from near the end of level 11 all the way to level 13, so let's do it before that happens).

We have an argument for target level which defaults to 13, so we should wrap trySkill(Feel Pride) in an externalIf() call to ensure that `myLevel() >= args.targetlevel - 2`.

**Comment by Alium58** [comment]
Great comments! The external if I stole from the glitch fight but makes sense that trySkill takes care of the checks.

Updated glitch fight to always try `feel pride` and then changed external if for NEP/gators to only use feel pride based on level like you suggest. 

This might be out of scope but also made the two glitch fights use the same combat macro. I think garbo fights glitch as well so an option would be to remove the aftercore glitch fight from goorbo since we don't need the stats at that time... does look like there is a pref to fight glitch though.

Haven't tested these latest changes yet.

**Review by frazazel — APPROVED** [review]
Looks good. Thanks for the changes!

**Comment by frazazel** [comment]
I don't see that you made a corresponding change to the bowl sideways externalIf(), but I'm happy to accept and make that last change on this end. Thanks for submitting!

**Pull request merged**
